### PR TITLE
Remove pip dependency from python base

### LINKED ISSUE #11: Base package is broken with new pip version
``pip.get_installed_distributions`` no longer works with pip version 10.

### PR DESCRIPTION
**Pull request by greschd**
Fixes #11.

Since ``pip`` doesn't have a publicly documented API, the can (and did) change the functions we relied on to get the installed ``fsc`` submodules.

This change gets rid of the ``pip`` dependency, using the ``pkg_resources`` provided by ``setuptools`` instead.

Also fixes "leaking" variable names from inside list comprehensions (affected only Python 2).

### CODE REVIEW

**Comment by greschd** [comment]
After merging, this needs to be released as a new version of the base package.

**Comment by mskoenz** [comment]
python3.6 & pip10: works well
python2.7 & pip10: fails

what I did:

```
git clone --recursive git@github.com:FrescolinoGroup/Frescolino.git
cd Frescolino
git checkout
git checkout remove_pip_dependency_from_python_base
cd helpers/python_fsc_base
pip install -e .
python
```

```python
>>> import fsc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fsc/__init__.py", line 24, in <module>
    _importlib.import_module(_modname.replace("-", "_"), package='fsc')
  File "/Users/mskoenz/.pyenv/versions/2.7.14/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named formatting
>>>
```

**Comment by greschd** [comment]
https://stackoverflow.com/questions/13400291/namespace-packages-and-pip-install-e

**Comment by greschd** [comment]
I'd say it works as intended on our part.

**Comment by mskoenz** [comment]
Sure, merge pull request accepted, this seems like a pip issue, not an fsc one...

**Pull request merged**
